[
    {
        "WfName": "inputString",
        "AcessPermission": "Public", 
        "AuthGroups": ["Basundhara Owners"],
        "AuthUsersADId": [],
        "AuthUsersEmpId": [],  
        "DisplayTxt": "View Report",
        "ViewUrl": { "siteUrl": "api/Report?type=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CBP-" },
        "MasterListInfo": { "name": "View Report", "select": "All"},
        "RenderDetListInfo": [{ "name": "View Report", "select": "All"}],
        "DetailsListInfo": [{ "name": "View Report", "select": "All"},
        { "name": "View Report", "select": "All"}],
        "DbViewColDef": [
            { "fldType": "TextField", "headerName": "Section", "field": "section", "editable":false, "minWidth": 150, "rowGroup": false, "hide": true },
            { "fldType": "TextField", "headerName": "Sub Section", "field": "subSection", "editable":true, "minWidth": 165, "rowGroup": false, "hide": true },
            { "fldType": "TextField", "headerName": "Schema Type", "field": "schema.type", "editable":true, "minWidth": 140, "rowGroup": false, "hide": false },            
            { "fldType": "TextField", "headerName": "Form Control Name", "field": "control", "editable":false, "minWidth": 170, "rowGroup": false, "hide": false },
            { "fldType": "TextField", "headerName": "Place Holder", "field": "placeHolder", "editable":true, "minWidth": 165, "hide": true },
            { "fldType": "TextField", "headerName": "Label Text", "field": "name", "editable":true, "minWidth": 200, "rowGroup": false, "hide": true }, 
            { "fldType": "TextField", "headerName": "Error Message", "field": "errorMessage", "editable":true, "minWidth": 200, "rowGroup": false, "hide": true }, 
            { "fldType": "TextField", "headerName": "Description", "field": "description", "editable":true, "minWidth": 200, "rowGroup": false, "hide": true }, 
            { "fldType": "TextField", "headerName": "Value", "field": "value", "editable":true, "minWidth": 100, "rowGroup": false, "hide": false }
        ]
    },
    {
        "WfName": "inputInteger",
        "AcessPermission": "Public", 
        "AuthGroups": ["Basundhara Owners"],
        "AuthUsersADId": [],
        "AuthUsersEmpId": [],  
        "DisplayTxt": "View Report",
        "ViewUrl": { "siteUrl": "api/Report?type=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CBP-" },
        "MasterListInfo": { "name": "View Report", "select": "All"},
        "RenderDetListInfo": [{ "name": "View Report", "select": "All"}],
        "DetailsListInfo": [{ "name": "View Report", "select": "All"},
        { "name": "View Report", "select": "All"}],
        "DbViewColDef": [
            { "fldType": "TextField", "headerName": "Section", "field": "section", "editable":false, "minWidth": 150, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Sub Section", "field": "subSection", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Type", "field": "schema.type", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Form Control Name", "field": "control", "editable":false, "minWidth": 160, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Place Holder", "field": "placeHolder", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Label Text", "field": "name", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Error Message", "field": "errorMessage", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Description", "field": "description", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Value", "field": "value", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "OutputView", "field": "outputView", "editable":true, "minWidth": 200, "rowGroup": false, "cellRenderer": "loadingRenderer" }
        ]
    },
    {
        "WfName": "inputNumber",
        "AcessPermission": "Public", 
        "AuthGroups": ["Basundhara Owners"],
        "AuthUsersADId": [],
        "AuthUsersEmpId": [],  
        "DisplayTxt": "View Report",
        "ViewUrl": { "siteUrl": "api/Report?type=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CBP-" },
        "MasterListInfo": { "name": "View Report", "select": "All"},
        "RenderDetListInfo": [{ "name": "View Report", "select": "All"}],
        "DetailsListInfo": [{ "name": "View Report", "select": "All"},
        { "name": "View Report", "select": "All"}],
        "DbViewColDef": [
            { "fldType": "TextField", "headerName": "Section", "field": "section", "editable":false, "minWidth": 150, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Sub Section", "field": "subSection", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Type", "field": "schema.type", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Form Control Name", "field": "control", "editable":false, "minWidth": 160, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Place Holder", "field": "placeHolder", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Label Text", "field": "name", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Error Message", "field": "errorMessage", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Description", "field": "description", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Value", "field": "value", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "OutputView", "field": "outputView", "editable":true, "minWidth": 200, "rowGroup": false, "cellRenderer": "loadingRenderer" }
        ]
    },
    {
        "WfName": "select",
        "AcessPermission": "Public", 
        "AuthGroups": ["Basundhara Owners"],
        "AuthUsersADId": [],
        "AuthUsersEmpId": [],  
        "DisplayTxt": "View Report",
        "ViewUrl": { "siteUrl": "api/Report?type=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CBP-" },
        "MasterListInfo": { "name": "View Report", "select": "All"},
        "RenderDetListInfo": [{ "name": "View Report", "select": "All"}],
        "DetailsListInfo": [{ "name": "View Report", "select": "All"},
        { "name": "View Report", "select": "All"}],
        "DbViewColDef": [
            { "fldType": "TextField", "headerName": "Section", "field": "section", "editable":false, "minWidth": 150, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Sub Section", "field": "subSection", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Type", "field": "schema.type", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Widget", "field": "schema.widget", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Choices Url", "field": "schema.choicesUrl", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Choices Verb", "field": "schema.choicesVerb", "editable":true, "minWidth": 165, "rowGroup": false },                        
            { "fldType": "TextField", "headerName": "Form Control Name", "field": "control", "editable":false, "minWidth": 160, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Place Holder", "field": "placeHolder", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Label Text", "field": "name", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Error Message", "field": "errorMessage", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Description", "field": "description", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Value", "field": "value", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "OutputView", "field": "outputView", "editable":true, "minWidth": 200, "rowGroup": false, "cellRenderer": "loadingRenderer" }
        ]
    },
    {
        "WfName": "multiSelect",
        "AcessPermission": "Public", 
        "AuthGroups": ["Basundhara Owners"],
        "AuthUsersADId": [],
        "AuthUsersEmpId": [],  
        "DisplayTxt": "View Report",
        "ViewUrl": { "siteUrl": "api/Report?type=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CBP-" },
        "MasterListInfo": { "name": "View Report", "select": "All"},
        "RenderDetListInfo": [{ "name": "View Report", "select": "All"}],
        "DetailsListInfo": [{ "name": "View Report", "select": "All"},
        { "name": "View Report", "select": "All"}],
        "DbViewColDef": [
            { "fldType": "TextField", "headerName": "Section", "field": "section", "editable":false, "minWidth": 150, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Sub Section", "field": "subSection", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Type", "field": "schema.type", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Items Type", "field": "schema.items.type", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Choices Url", "field": "schema.choicesUrl", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Choices Verb", "field": "schema.choicesVerb", "editable":true, "minWidth": 165, "rowGroup": false },                        
            { "fldType": "TextField", "headerName": "Form Control Name", "field": "control", "editable":false, "minWidth": 160, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Place Holder", "field": "placeHolder", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Label Text", "field": "name", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Error Message", "field": "errorMessage", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Description", "field": "description", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Value", "field": "value", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "OutputView", "field": "outputView", "editable":true, "minWidth": 200, "rowGroup": false, "cellRenderer": "loadingRenderer" }
        ]
    },
    {
        "WfName": "radio",
        "AcessPermission": "Public", 
        "AuthGroups": ["Basundhara Owners"],
        "AuthUsersADId": [],
        "AuthUsersEmpId": [],  
        "DisplayTxt": "View Report",
        "ViewUrl": { "siteUrl": "api/Report?type=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CBP-" },
        "MasterListInfo": { "name": "View Report", "select": "All"},
        "RenderDetListInfo": [{ "name": "View Report", "select": "All"}],
        "DetailsListInfo": [{ "name": "View Report", "select": "All"},
        { "name": "View Report", "select": "All"}],
        "DbViewColDef": [
            { "fldType": "TextField", "headerName": "Section", "field": "section", "editable":false, "minWidth": 150, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Sub Section", "field": "subSection", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Type", "field": "schema.type", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Widget", "field": "schema.widget", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Choices Url", "field": "schema.choicesUrl", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Choices Verb", "field": "schema.choicesVerb", "editable":true, "minWidth": 165, "rowGroup": false },                        
            { "fldType": "TextField", "headerName": "Form Control Name", "field": "control", "editable":false, "minWidth": 160, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Place Holder", "field": "placeHolder", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Label Text", "field": "name", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Error Message", "field": "errorMessage", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Description", "field": "description", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Value", "field": "value", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "OutputView", "field": "outputView", "editable":true, "minWidth": 200, "rowGroup": false, "cellRenderer": "loadingRenderer" }
        ]
    },
    {
        "WfName": "date",
        "AcessPermission": "Public", 
        "AuthGroups": ["Basundhara Owners"],
        "AuthUsersADId": [],
        "AuthUsersEmpId": [],  
        "DisplayTxt": "View Report",
        "ViewUrl": { "siteUrl": "api/Report?type=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CBP-" },
        "MasterListInfo": { "name": "View Report", "select": "All"},
        "RenderDetListInfo": [{ "name": "View Report", "select": "All"}],
        "DetailsListInfo": [{ "name": "View Report", "select": "All"},
        { "name": "View Report", "select": "All"}],
        "DbViewColDef": [
            { "fldType": "TextField", "headerName": "Section", "field": "section", "editable":false, "minWidth": 150, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Sub Section", "field": "subSection", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Type", "field": "schema.type", "editable":true, "minWidth": 165, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Schema Widget", "field": "schema.widget", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Date Formate", "field": "schema.dateFormat", "editable":true, "minWidth": 165, "rowGroup": false },            
            { "fldType": "TextField", "headerName": "Form Control Name", "field": "control", "editable":false, "minWidth": 160, "rowGroup": false },
            { "fldType": "TextField", "headerName": "Place Holder", "field": "placeHolder", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Label Text", "field": "name", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Error Message", "field": "errorMessage", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Description", "field": "description", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "Value", "field": "value", "editable":true, "minWidth": 200, "rowGroup": false }, 
            { "fldType": "TextField", "headerName": "OutputView", "field": "outputView", "editable":true, "minWidth": 200, "rowGroup": false, "cellRenderer": "loadingRenderer" }
        ]
    },    
    {
        "WfName": "Email Report",
        "AcessPermission": "Public", 
        "AuthGroups": ["Basundhara Owners"],
        "AuthUsersADId": [],
        "AuthUsersEmpId": [],  
        "DisplayTxt": "View Report",
        "ViewUrl": { "siteUrl": "api/Report?type=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CBP-" },
        "MasterListInfo": { "name": "View Report", "select": "All"},
        "RenderDetListInfo": [{ "name": "View Report", "select": "All"}],
        "DetailsListInfo": [{ "name": "View Report", "select": "All"},
        { "name": "View Report", "select": "All"}],
        "DbViewColDef": [
            { "fldType": "TextField", "headerName": "Project Name", "field": "projectName", "editable":true, "minWidth": 150 },
            { "fldType": "TextField", "headerName": "Document Type", "field": "documentType", "editable":false, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "R File No", "field": "rFileNo", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "Deed No", "field": "deedNo", "editable":false, "minWidth": 120 },            
            { "fldType": "GetSetDateField", "headerName": "Document Date", "field": "documentDate", "valueGetter":"documentDate", "editable":false, "minWidth": 150 },            
            { "fldType": "TextField", "headerName": "Mouza", "field": "mouza", "editable":false, "minWidth": 150, "hide":true },
            { "fldType": "TextField", "headerName": "Phase Name", "field": "phaseName", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "User Name", "field": "UserName", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Recipient", "field": "Recipient", "editable":true, "minWidth": 165 },
            { "fldType": "GetSetDateField", "headerName": "Date Time", "field": "dateTime", "valueGetter":"dateTime", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "IP Address", "field": "ipAddress", "editable":true, "minWidth": 200 }
        ],
        "MasterDetailViewColDef": [
            { "fldType": "TextField", "headerName": "Project Name", "field": "projectName", "editable":true, "minWidth": 150 },
            { "fldType": "TextField", "headerName": "Document Type", "field": "documentType", "editable":false, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "R File No", "field": "rFileNo", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "Deed No", "field": "deedNo", "editable":false, "minWidth": 120 },
            { "fldType": "GetSetDateField", "headerName": "Document Date", "field": "documentDate", "valueGetter":"documentDate", "editable":false, "minWidth": 150 },
            { "fldType": "TextField", "headerName": "Mouza", "field": "mouza", "editable":false, "minWidth": 100, "hide":true },
            { "fldType": "TextField", "headerName": "Phase Name", "field": "phaseName", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "User Name", "field": "UserName", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Recipient", "field": "Recipient", "editable":true, "minWidth": 165 },
            { "fldType": "GetSetDateField", "headerName": "Date Time", "field": "dateTime", "valueGetter":"dateTime", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "IP Address", "field": "ipAddress", "editable":true, "minWidth": 200 }
        ]
    }

 
]
